# -*- coding: utf-8 -*-
"""Base_sheets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T7-PCckB0OsU6ROpENndhpetAnl5Z2sL
"""

import streamlit as st
from streamlit_gsheets import GSheetsConnection
import pandas as pd

st.title(" Test de conexión con Google Sheets")

try:
    # Crear la conexión (lee los secrets automáticamente)
    conn = st.connection("gsheets", type=GSheetsConnection)
    st.success("✅ Conexión con Google Sheets establecida")

    # Leer la pestaña 'estado'
    df = conn.read(worksheet="estado", ttl=0)
    st.write("📄 Contenido de la pestaña 'estado':")
    st.dataframe(df)

    # Mostrar info de las otras pestañas
    with st.expander("📄 Pestaña 'movimientos'"):
        df2 = conn.read(worksheet="movimientos", ttl=0)
        st.dataframe(df2)

    with st.expander("📄 Pestaña 'snapshots'"):
        df3 = conn.read(worksheet="snapshots", ttl=0)
        st.dataframe(df3)

except Exception as e:
    st.error(f"❌ Error: {e}")
    st.exception(e)