# -*- coding: utf-8 -*-
"""Base_contcerd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FWVeC8xEfzwn7cyuMpGM8L82c62JDuGk
"""

import streamlit as st
import sqlite3
from datetime import datetime, date
import threading
import time
from pathlib import Path

DB_PATH = "granja.db"

# ---------------- BASE DE DATOS ----------------
def init_db():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute("""CREATE TABLE IF NOT EXISTS estado (
        id TEXT PRIMARY KEY,
        caseta INTEGER,
        corral TEXT,
        poblacion INTEGER
    )""")
    c.execute("""CREATE TABLE IF NOT EXISTS movimientos (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        timestamp TEXT,
        unidad_id TEXT,
        valor_anterior INTEGER,
        valor_nuevo INTEGER,
        delta INTEGER,
        motivo TEXT
    )""")
    c.execute("""CREATE TABLE IF NOT EXISTS snapshots (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        fecha TEXT,
        unidad_id TEXT,
        poblacion INTEGER
    )""")
    # Inicializar las 18 unidades por caseta: 16 corrales + 2 enfermerías
    for caseta in range(1, 5):
        for i in range(1, 17):  # 1..16
            uid = f"{caseta}-{i}"
            c.execute("INSERT OR IGNORE INTO estado VALUES (?,?,?,?)",
                      (uid, caseta, str(i), 0))
        for e in ["E1", "E2"]:
            uid = f"{caseta}-{e}"
            c.execute("INSERT OR IGNORE INTO estado VALUES (?,?,?,?)",
                      (uid, caseta, e, 0))
    conn.commit()
    conn.close()

def get_estado():
    conn = sqlite3.connect(DB_PATH)
    df = conn.execute("SELECT id, caseta, corral, poblacion FROM estado").fetchall()
    conn.close()
    return {row[0]: row[3] for row in df}

def get_poblacion(estado, uid):
    """Devuelve la población o 0 si la unidad no existe (evita KeyError)."""
    return estado.get(uid, 0)

def set_poblacion(unidad_id, nuevo_valor, motivo="ajuste manual"):
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    anterior = c.execute("SELECT poblacion FROM estado WHERE id=?", (unidad_id,)).fetchone()[0]
    if anterior == nuevo_valor:
        conn.close()
        return
    c.execute("UPDATE estado SET poblacion=? WHERE id=?", (nuevo_valor, unidad_id))
    c.execute("""INSERT INTO movimientos (timestamp, unidad_id, valor_anterior, valor_nuevo, delta, motivo)
                 VALUES (?,?,?,?,?,?)""",
              (datetime.now().isoformat(), unidad_id, anterior, nuevo_valor,
               nuevo_valor - anterior, motivo))
    conn.commit()
    conn.close()

def guardar_snapshot(motivo="manual"):
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    hoy = date.today().isoformat()
    filas = c.execute("SELECT id, poblacion FROM estado").fetchall()
    for uid, pob in filas:
        c.execute("INSERT INTO snapshots (fecha, unidad_id, poblacion) VALUES (?,?,?)",
                  (hoy, uid, pob))
    conn.commit()
    conn.close()
    return len(filas)

# ---------------- GUARDADO AUTOMÁTICO A MEDIANOCHE ----------------
def scheduler_medianoche():
    while True:
        ahora = datetime.now()
        # Segundos hasta la próxima medianoche
        manana = datetime(ahora.year, ahora.month, ahora.day) + __import__("datetime").timedelta(days=1)
        espera = (manana - ahora).total_seconds()
        time.sleep(espera)
        guardar_snapshot("automático medianoche")

@st.cache_resource
def iniciar_scheduler():
    t = threading.Thread(target=scheduler_medianoche, daemon=True)
    t.start()
    return True

# ---------------- UI ----------------
st.set_page_config(page_title="Granja de cerdos", layout="wide")
init_db()
iniciar_scheduler()



# ---------------- EDITOR DE CADA UNIDAD ----------------
def render_unidad(uid, poblacion, compacto=False):
    """Renderiza una unidad (corral o enfermería)."""
    with st.container(border=True):
        st.markdown(f"**{uid}**")
        st.markdown(f"<div style='font-size:22px;font-weight:bold;text-align:center'>{poblacion}</div>",
                    unsafe_allow_html=True)
        with st.popover("✏️ Editar", use_container_width=True):
            modo = st.radio("Modo", ["Ajustar total", "Sumar/Restar"],
                            key=f"modo_{uid}", horizontal=True)
            if modo == "Ajustar total":
                nuevo = st.number_input("Nueva población", min_value=0,
                                        value=poblacion, key=f"num_{uid}")
                motivo = st.text_input("Motivo", key=f"mot_{uid}",
                                       placeholder="ej: movimiento, venta...")
                if st.button("Guardar", key=f"save_{uid}", use_container_width=True):
                    set_poblacion(uid, int(nuevo), motivo or "ajuste total")
                    st.rerun()
            else:
                delta = st.number_input("Cantidad (+/-)", value=0, step=1,
                                        key=f"delta_{uid}")
                motivo = st.text_input("Motivo", key=f"motd_{uid}",
                                       placeholder="ej: muerte, nacimiento...")
                if st.button("Aplicar", key=f"apply_{uid}", use_container_width=True):
                    nuevo = max(0, poblacion + int(delta))
                    set_poblacion(uid, nuevo, motivo or "ajuste delta")
                    st.rerun()

# ---------------- RENDER DE CADA CASETA ----------------
def render_caseta(caseta):
    st.subheader(f"🏠 Caseta {caseta}")
    with st.container(border=True):
        # Fila superior: enfermerías al norte
        c_izq, c_pas, c_der = st.columns([4, 1, 4])
        with c_izq:
            sub = st.columns(8)
            with sub[0]:
                uid = f"{caseta}-E1"
                render_unidad(uid, estado.get(uid, 0), compacto=True)
        with c_der:
            sub = st.columns(8)
            with sub[7]:
                uid = f"{caseta}-E2"
                render_unidad(uid, estado.get(uid, 0), compacto=True)

        st.markdown("<div style='text-align:center;color:gray'>— pasillo central —</div>",
                    unsafe_allow_html=True)

        # Lado izquierdo: corrales 1-8
        izq, der = st.columns(2)
        with izq:
            cols = st.columns(8)
            for i in range(1, 9):
                with cols[i - 1]:
                    uid = f"{caseta}-{i}"
                    render_unidad(uid, estado.get(uid, 0))
        # Lado derecho: corrales 9-16
        with der:
            cols = st.columns(8)
            for i in range(9, 17):
                with cols[i - 9]:
                    uid = f"{caseta}-{i}"
                    render_unidad(uid, estado.get(uid, 0))

# ==================== RENDER PRINCIPAL ====================

st.title("🐖 Control de población - Granja")

estado = get_estado()

# Barra superior: totales y botón guardar
total = sum(estado.values())
col1, col2, col3 = st.columns([2, 1, 1])
col1.metric("Población total", total)
if col2.button("💾 Guardar snapshot manual", use_container_width=True):
    n = guardar_snapshot("manual")
    st.success(f"Snapshot guardado ({n} unidades)")
if col3.button("🔄 Refrescar", use_container_width=True):
    st.rerun()

# Debug temporal
with st.expander("🔍 Debug (quitar después)"):
    st.write(f"Unidades en DB: {len(estado)}")
    st.write(f"Primeras 5: {list(estado.items())[:5]}")

# Render de las 4 casetas
for c in range(1, 5):
    render_caseta(c)
    st.markdown("---")

# ---------------- AUDITORÍA ----------------
with st.expander("📜 Historial de movimientos"):
    conn = sqlite3.connect(DB_PATH)
    rows = conn.execute("""SELECT timestamp, unidad_id, valor_anterior, valor_nuevo, delta, motivo
                           FROM movimientos ORDER BY id DESC LIMIT 200""").fetchall()
    conn.close()
    if rows:
        st.dataframe(rows, use_container_width=True,
                     column_config={
                         0: "Fecha", 1: "Unidad", 2: "Antes",
                         3: "Después", 4: "Δ", 5: "Motivo"
                     })
    else:
        st.info("Sin movimientos registrados aún.")

with st.expander("📸 Snapshots guardados"):
    conn = sqlite3.connect(DB_PATH)
    rows = conn.execute("""SELECT fecha, COUNT(*), SUM(poblacion)
                           FROM snapshots GROUP BY fecha ORDER BY fecha DESC""").fetchall()
    conn.close()
    if rows:
        st.dataframe(rows, use_container_width=True,
                     column_config={0: "Fecha", 1: "Unidades", 2: "Total cerdos"})
    else:
        st.info("Sin snapshots guardados aún.")