# -*- coding: utf-8 -*-
"""Base_contcerd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FWVeC8xEfzwn7cyuMpGM8L82c62JDuGk
"""

import streamlit as st
import gspread
from google.oauth2.service_account import Credentials
import pandas as pd
from datetime import datetime, date
import threading
import time

# ==================== CONEXIÓN CON GOOGLE SHEETS ====================
SPREADSHEET_ID = "10aCfWrVTpIbXGMrM-TbQ4R_xFT7xP9ShtCgQN8go0LI"

@st.cache_resource
def get_client():
    scopes = [
        "https://www.googleapis.com/auth/spreadsheets",
        "https://www.googleapis.com/auth/drive"
    ]
    creds_dict = dict(st.secrets["gcp_service_account"])
    creds = Credentials.from_service_account_info(creds_dict, scopes=scopes)
    return gspread.authorize(creds)

@st.cache_resource
def get_spreadsheet():
    return get_client().open_by_key(SPREADSHEET_ID)

# ==================== FUNCIONES DE BASE DE DATOS ====================
def init_hojas():
    """Crea las 72 filas iniciales en la pestaña 'estado' si no existen."""
    sh = get_spreadsheet()
    ws = sh.worksheet("estado")
    valores = ws.get_all_values()

    # Si solo tiene encabezados, llenamos las 72 unidades
    if len(valores) <= 1:
        filas = []
        for caseta in range(1, 5):
            for i in range(1, 17):
                filas.append([f"{caseta}-{i}", str(caseta), str(i), "0"])
            for e in ["E1", "E2"]:
                filas.append([f"{caseta}-{e}", str(caseta), e, "0"])
        ws.append_rows(filas, value_input_option="USER_ENTERED")

def get_estado():
    """Lee la pestaña 'estado' y devuelve {id: poblacion}."""
    sh = get_spreadsheet()
    ws = sh.worksheet("estado")
    valores = ws.get_all_values()
    estado = {}
    for fila in valores[1:]:  # saltar encabezado
        if len(fila) >= 4 and fila[0]:
            try:
                estado[fila[0]] = int(fila[3]) if fila[3] else 0
            except ValueError:
                estado[fila[0]] = 0
    return estado

def set_poblacion(unidad_id, nuevo_valor, motivo="ajuste manual"):
    """Actualiza la población de una unidad y registra el movimiento."""
    sh = get_spreadsheet()
    ws_estado = sh.worksheet("estado")
    valores = ws_estado.get_all_values()

    # Buscar la fila del corral
    fila_idx = None
    valor_anterior = None
    for i, fila in enumerate(valores[1:], start=2):  # fila 2 en adelante
        if fila and fila[0] == unidad_id:
            fila_idx = i
            try:
                valor_anterior = int(fila[3]) if len(fila) > 3 and fila[3] else 0
            except ValueError:
                valor_anterior = 0
            break

    if fila_idx is None:
        st.error(f"No se encontró la unidad {unidad_id} en la hoja")
        return

    if valor_anterior == nuevo_valor:
        return

    # Actualizar población (columna D = 4)
    ws_estado.update_cell(fila_idx, 4, nuevo_valor)

    # Registrar movimiento en la pestaña 'movimientos'
    ws_mov = sh.worksheet("movimientos")
    ws_mov.append_row([
        datetime.now().isoformat(),
        unidad_id,
        str(valor_anterior),
        str(nuevo_valor),
        motivo
    ], value_input_option="USER_ENTERED")

    # Limpiar caché para que el próximo get_estado() traiga datos frescos
    st.cache_data.clear()

def guardar_snapshot(motivo="manual"):
    """Guarda un snapshot de todas las poblaciones en la pestaña 'snapshots'."""
    sh = get_spreadsheet()
    ws_estado = sh.worksheet("estado")
    valores = ws_estado.get_all_values()

    hoy = date.today().isoformat()
    filas = []
    for fila in valores[1:]:
        if fila and fila[0]:
            poblacion = fila[3] if len(fila) > 3 else "0"
            filas.append([hoy, fila[0], poblacion or "0"])

    ws_snap = sh.worksheet("snapshots")
    ws_snap.append_rows(filas, value_input_option="USER_ENTERED")
    return len(filas)

# ==================== GUARDADO AUTOMÁTICO A MEDIANOCHE ====================
def scheduler_medianoche():
    while True:
        ahora = datetime.now()
        manana = datetime(ahora.year, ahora.month, ahora.day) + \
                 __import__("datetime").timedelta(days=1)
        espera = (manana - ahora).total_seconds()
        time.sleep(espera)
        try:
            guardar_snapshot("automático medianoche")
        except Exception as e:
            print(f"Error en snapshot automático: {e}")

@st.cache_resource
def iniciar_scheduler():
    t = threading.Thread(target=scheduler_medianoche, daemon=True)
    t.start()
    return True

# ==================== CONFIGURACIÓN INICIAL ====================
st.set_page_config(page_title="Granja de cerdos", layout="wide")
init_hojas()
iniciar_scheduler()

# ==================== RENDER DE CADA UNIDAD ====================
def render_unidad(uid, poblacion, compacto=False):
    with st.container(border=True):
        st.markdown(f"**{uid}**")
        st.markdown(
            f"<div style='font-size:22px;font-weight:bold;text-align:center'>{poblacion}</div>",
            unsafe_allow_html=True
        )
        with st.popover("✏️ Editar", width="stretch"):
            modo = st.radio("Modo", ["Ajustar total", "Sumar/Restar"],
                            key=f"modo_{uid}", horizontal=True)
            if modo == "Ajustar total":
                nuevo = st.number_input("Nueva población", min_value=0,
                                        value=poblacion, key=f"num_{uid}")
                motivo = st.text_input("Motivo", key=f"mot_{uid}",
                                       placeholder="ej: movimiento, venta...")
                if st.button("Guardar", key=f"save_{uid}", width="stretch"):
                    set_poblacion(uid, int(nuevo), motivo or "ajuste total")
                    st.rerun()
            else:
                delta = st.number_input("Cantidad (+/-)", value=0, step=1,
                                        key=f"delta_{uid}")
                motivo = st.text_input("Motivo", key=f"motd_{uid}",
                                       placeholder="ej: muerte, nacimiento...")
                if st.button("Aplicar", key=f"apply_{uid}", width="stretch"):
                    nuevo = max(0, poblacion + int(delta))
                    set_poblacion(uid, nuevo, motivo or "ajuste delta")
                    st.rerun()

# ==================== RENDER DE CADA CASETA ====================
def render_caseta(caseta):
    st.subheader(f"🏠 Caseta {caseta}")

    filas = [("E1", "E2")]
    for fila in range(8):
        filas.append((str(1 + fila * 2), str(2 + fila * 2)))

    html = '<div style="display:flex; justify-content:center; padding:10px; background:#eaf4fb; border-radius:12px; border:1px solid #b0c4de;"><table style="border-collapse:separate; border-spacing:0 6px;">'

    for izq_id, der_id in filas:
        uid_izq = f"{caseta}-{izq_id}"
        uid_der = f"{caseta}-{der_id}"
        pob_izq = estado.get(uid_izq, 0)
        pob_der = estado.get(uid_der, 0)

        es_enfermeria = izq_id.startswith("E")
        ancho = "70px" if es_enfermeria else "130px"
        alto = "50px" if es_enfermeria else "auto"

        html += (
            f'<tr>'
            f'<td style="width:{ancho}; min-width:{ancho}; height:{alto}; background:#c9dff0; border:1px solid #7a9cbf; border-radius:4px; text-align:center; vertical-align:middle; padding:6px; font-size:12px; color:#1a3d5c;">'
            f'<b>{uid_izq}</b><br><span style="font-size:16px;">{pob_izq}</span>'
            f'</td>'
            f'<td style="width:60px;"></td>'
            f'<td style="width:{ancho}; min-width:{ancho}; height:{alto}; background:#c9dff0; border:1px solid #7a9cbf; border-radius:4px; text-align:center; vertical-align:middle; padding:6px; font-size:12px; color:#1a3d5c;">'
            f'<b>{uid_der}</b><br><span style="font-size:16px;">{pob_der}</span>'
            f'</td>'
            f'</tr>'
        )

    html += '</table></div>'
    st.markdown(html, unsafe_allow_html=True)

    with st.expander(f"✏️ Editar corrales de Caseta {caseta}"):
        cols = st.columns(6)
        todos_ids = [f"{caseta}-E1", f"{caseta}-E2"] + \
                    [f"{caseta}-{i}" for i in range(1, 17)]

        for idx, uid in enumerate(todos_ids):
            with cols[idx % 6]:
                pob = estado.get(uid, 0)
                if st.button(f"{uid} ({pob})", key=f"editbtn_{uid}",
                             width="stretch"):
                    st.session_state[f"editar_{uid}"] = True

        for uid in todos_ids:
            if st.session_state.get(f"editar_{uid}", False):
                pob = estado.get(uid, 0)
                st.markdown(f"#### Editando **{uid}** (actual: {pob})")
                c1, c2, c3 = st.columns([1, 1, 1])
                with c1:
                    nuevo = st.number_input("Nueva población", min_value=0,
                                            value=pob, key=f"editnum_{uid}")
                with c2:
                    motivo = st.text_input("Motivo", key=f"editmot_{uid}",
                                           placeholder="ej: venta, muerte...")
                with c3:
                    st.write("")
                    st.write("")
                    if st.button("💾 Guardar", key=f"editsave_{uid}",
                                 width="stretch"):
                        set_poblacion(uid, int(nuevo), motivo or "ajuste manual")
                        st.session_state[f"editar_{uid}"] = False
                        st.rerun()
                    if st.button("❌ Cancelar", key=f"editcancel_{uid}",
                                 width="stretch"):
                        st.session_state[f"editar_{uid}"] = False
                        st.rerun()

# ==================== RENDER PRINCIPAL ====================
st.title("🐖 Control de población - Granja")

with st.spinner("Cargando datos desde Google Sheets..."):
    estado = get_estado()

total = sum(estado.values())
col1, col2, col3 = st.columns([2, 1, 1])
col1.metric("Población total", total)
if col2.button("💾 Guardar snapshot manual", width="stretch"):
    with st.spinner("Guardando snapshot..."):
        n = guardar_snapshot("manual")
    st.success(f"Snapshot guardado ({n} unidades)")
if col3.button("🔄 Refrescar", width="stretch"):
    st.cache_data.clear()
    st.rerun()

# Render de las 4 casetas
for c in range(1, 5):
    render_caseta(c)
    st.markdown("---")

# ==================== AUDITORÍA ====================
with st.expander("📜 Historial de movimientos"):
    try:
        sh = get_spreadsheet()
        ws = sh.worksheet("movimientos")
        valores = ws.get_all_values()
        if len(valores) > 1:
            df = pd.DataFrame(valores[1:],
                              columns=["Fecha", "Unidad", "Antes", "Después", "Motivo"])
            # Calcular delta
            try:
                df["Δ"] = df["Después"].astype(int) - df["Antes"].astype(int)
            except ValueError:
                df["Δ"] = ""
            df = df[["Fecha", "Unidad", "Antes", "Después", "Δ", "Motivo"]]
            # Formatear fecha
            try:
                df["Fecha"] = pd.to_datetime(df["Fecha"]).dt.strftime("%Y-%m-%d %H:%M:%S")
            except Exception:
                pass
            # Mostrar los últimos 200 (más recientes primero)
            df = df.iloc[::-1].head(200)
            st.dataframe(df, width="stretch")
        else:
            st.info("Sin movimientos registrados aún.")
    except Exception as e:
        st.error(f"Error leyendo movimientos: {e}")

with st.expander("📸 Snapshots guardados"):
    try:
        sh = get_spreadsheet()
        ws = sh.worksheet("snapshots")
        valores = ws.get_all_values()
        if len(valores) > 1:
            df = pd.DataFrame(valores[1:], columns=["Fecha", "Unidad", "Población"])
            # Agrupar por fecha
            resumen = df.groupby("Fecha").agg(
                Unidades=("Unidad", "count"),
                Total=("Población", lambda x: pd.to_numeric(x, errors="coerce").sum())
            ).reset_index().sort_values("Fecha", ascending=False)
            st.dataframe(resumen, width="stretch")
        else:
            st.info("Sin snapshots guardados aún.")
    except Exception as e:
        st.error(f"Error leyendo snapshots: {e}")
