# -*- coding: utf-8 -*-
"""Base_contcerd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FWVeC8xEfzwn7cyuMpGM8L82c62JDuGk
"""

import streamlit as st
import sqlite3
from datetime import datetime, date
import threading
import time

DB_PATH = "granja.db"

# ---------------- BASE DE DATOS ----------------
def init_db():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute("""CREATE TABLE IF NOT EXISTS estado (
        id TEXT PRIMARY KEY,
        caseta INTEGER,
        corral TEXT,
        poblacion INTEGER
    )""")
    c.execute("""CREATE TABLE IF NOT EXISTS movimientos (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        timestamp TEXT,
        unidad_id TEXT,
        valor_anterior INTEGER,
        valor_nuevo INTEGER,
        delta INTEGER,
        motivo TEXT
    )""")
    c.execute("""CREATE TABLE IF NOT EXISTS snapshots (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        fecha TEXT,
        unidad_id TEXT,
        poblacion INTEGER
    )""")
    # Inicializar las 18 unidades por caseta: 16 corrales + 2 enfermerías
    for caseta in range(1, 5):
        for i in range(1, 17):  # 1..16
            uid = f"{caseta}-{i}"
            c.execute("INSERT OR IGNORE INTO estado VALUES (?,?,?,?)",
                      (uid, caseta, str(i), 0))
        for e in ["E1", "E2"]:
            uid = f"{caseta}-{e}"
            c.execute("INSERT OR IGNORE INTO estado VALUES (?,?,?,?)",
                      (uid, caseta, e, 0))
    conn.commit()
    conn.close()

def get_estado():
    conn = sqlite3.connect(DB_PATH)
    df = conn.execute("SELECT id, caseta, corral, poblacion FROM estado").fetchall()
    conn.close()
    return {row[0]: row[3] for row in df}

def get_poblacion(estado, uid):
    """Devuelve la población o 0 si la unidad no existe (evita KeyError)."""
    return estado.get(uid, 0)

def set_poblacion(unidad_id, nuevo_valor, motivo="ajuste manual"):
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    anterior = c.execute("SELECT poblacion FROM estado WHERE id=?", (unidad_id,)).fetchone()[0]
    if anterior == nuevo_valor:
        conn.close()
        return
    c.execute("UPDATE estado SET poblacion=? WHERE id=?", (nuevo_valor, unidad_id))
    c.execute("""INSERT INTO movimientos (timestamp, unidad_id, valor_anterior, valor_nuevo, delta, motivo)
                 VALUES (?,?,?,?,?,?)""",
              (datetime.now().isoformat(), unidad_id, anterior, nuevo_valor,
               nuevo_valor - anterior, motivo))
    conn.commit()
    conn.close()

def guardar_snapshot(motivo="manual"):
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    hoy = date.today().isoformat()
    filas = c.execute("SELECT id, poblacion FROM estado").fetchall()
    for uid, pob in filas:
        c.execute("INSERT INTO snapshots (fecha, unidad_id, poblacion) VALUES (?,?,?)",
                  (hoy, uid, pob))
    conn.commit()
    conn.close()
    return len(filas)

# ---------------- GUARDADO AUTOMÁTICO A MEDIANOCHE ----------------
def scheduler_medianoche():
    while True:
        ahora = datetime.now()
        # Segundos hasta la próxima medianoche
        manana = datetime(ahora.year, ahora.month, ahora.day) + __import__("datetime").timedelta(days=1)
        espera = (manana - ahora).total_seconds()
        time.sleep(espera)
        guardar_snapshot("automático medianoche")

@st.cache_resource
def iniciar_scheduler():
    t = threading.Thread(target=scheduler_medianoche, daemon=True)
    t.start()
    return True

# ---------------- UI ----------------
st.set_page_config(page_title="Granja de cerdos", layout="wide")
init_db()
iniciar_scheduler()



# ---------------- EDITOR DE CADA UNIDAD ----------------
def render_unidad(uid, poblacion, compacto=False):
    """Renderiza una unidad (corral o enfermería)."""
    with st.container(border=True):
        st.markdown(f"**{uid}**")
        st.markdown(f"<div style='font-size:22px;font-weight:bold;text-align:center'>{poblacion}</div>",
                    unsafe_allow_html=True)
        with st.popover("✏️ Editar", use_container_width=True):
            modo = st.radio("Modo", ["Ajustar total", "Sumar/Restar"],
                            key=f"modo_{uid}", horizontal=True)
            if modo == "Ajustar total":
                nuevo = st.number_input("Nueva población", min_value=0,
                                        value=poblacion, key=f"num_{uid}")
                motivo = st.text_input("Motivo", key=f"mot_{uid}",
                                       placeholder="ej: movimiento, venta...")
                if st.button("Guardar", key=f"save_{uid}", use_container_width=True):
                    set_poblacion(uid, int(nuevo), motivo or "ajuste total")
                    st.rerun()
            else:
                delta = st.number_input("Cantidad (+/-)", value=0, step=1,
                                        key=f"delta_{uid}")
                motivo = st.text_input("Motivo", key=f"motd_{uid}",
                                       placeholder="ej: muerte, nacimiento...")
                if st.button("Aplicar", key=f"apply_{uid}", use_container_width=True):
                    nuevo = max(0, poblacion + int(delta))
                    set_poblacion(uid, nuevo, motivo or "ajuste delta")
                    st.rerun()

# ---------------- RENDER DE CADA CASETA ----------------
def render_caseta(caseta):
    st.subheader(f"🏠 Caseta {caseta}")

    filas = [("E1", "E2")]
    for fila in range(8):
        filas.append((str(1 + fila * 2), str(2 + fila * 2)))

    # HTML completo SIN indentación (una sola línea para evitar que Markdown lo trate como código)
    html = '<div style="display:flex; justify-content:center; padding:10px; background:#eaf4fb; border-radius:12px; border:1px solid #b0c4de;"><table style="border-collapse:separate; border-spacing:0 6px;">'

    for izq_id, der_id in filas:
        uid_izq = f"{caseta}-{izq_id}"
        uid_der = f"{caseta}-{der_id}"
        pob_izq = estado.get(uid_izq, 0)
        pob_der = estado.get(uid_der, 0)

        es_enfermeria = izq_id.startswith("E")
        ancho = "70px" if es_enfermeria else "130px"
        alto = "50px" if es_enfermeria else "auto"

        html += (
            f'<tr>'
            f'<td style="width:{ancho}; min-width:{ancho}; height:{alto}; background:#c9dff0; border:1px solid #7a9cbf; border-radius:4px; text-align:center; vertical-align:middle; padding:6px; font-size:12px; color:#1a3d5c;">'
            f'<b>{uid_izq}</b><br><span style="font-size:16px;">{pob_izq}</span>'
            f'</td>'
            f'<td style="width:60px;"></td>'
            f'<td style="width:{ancho}; min-width:{ancho}; height:{alto}; background:#c9dff0; border:1px solid #7a9cbf; border-radius:4px; text-align:center; vertical-align:middle; padding:6px; font-size:12px; color:#1a3d5c;">'
            f'<b>{uid_der}</b><br><span style="font-size:16px;">{pob_der}</span>'
            f'</td>'
            f'</tr>'
        )

    html += '</table></div>'

    st.markdown(html, unsafe_allow_html=True)

    # Expander con botones de edición
    with st.expander(f"✏️ Editar corrales de Caseta {caseta}"):
        cols = st.columns(6)
        todos_ids = [f"{caseta}-E1", f"{caseta}-E2"] + \
                    [f"{caseta}-{i}" for i in range(1, 17)]

        for idx, uid in enumerate(todos_ids):
            with cols[idx % 6]:
                pob = estado.get(uid, 0)
                if st.button(f"{uid} ({pob})", key=f"editbtn_{uid}",
                             use_container_width=True):
                    st.session_state[f"editar_{uid}"] = True

        # Editor del corral seleccionado
        for uid in todos_ids:
            if st.session_state.get(f"editar_{uid}", False):
                pob = estado.get(uid, 0)
                st.markdown(f"#### Editando **{uid}** (actual: {pob})")
                c1, c2, c3 = st.columns([1, 1, 1])
                with c1:
                    nuevo = st.number_input("Nueva población", min_value=0,
                                            value=pob, key=f"editnum_{uid}")
                with c2:
                    motivo = st.text_input("Motivo", key=f"editmot_{uid}",
                                           placeholder="ej: venta, muerte...")
                with c3:
                    st.write("")
                    st.write("")
                    if st.button("💾 Guardar", key=f"editsave_{uid}",
                                 use_container_width=True):
                        set_poblacion(uid, int(nuevo), motivo or "ajuste manual")
                        st.session_state[f"editar_{uid}"] = False
                        st.rerun()
                    if st.button("❌ Cancelar", key=f"editcancel_{uid}",
                                 use_container_width=True):
                        st.session_state[f"editar_{uid}"] = False
                        st.rerun()


# ==================== RENDER PRINCIPAL ====================

st.title("Control de población - Granja")

estado = get_estado()

# Barra superior: totales y botón guardar
total = sum(estado.values())
col1, col2, col3 = st.columns([2, 1, 1])
col1.metric("Población total", total)
if col2.button("💾 Guardar snapshot manual", use_container_width=True):
    n = guardar_snapshot("manual")
    st.success(f"Snapshot guardado ({n} unidades)")
if col3.button("🔄 Refrescar", use_container_width=True):
    st.rerun()

# Debug temporal
with st.expander("🔍 Debug (quitar después)"):
    st.write(f"Unidades en DB: {len(estado)}")
    st.write(f"Primeras 5: {list(estado.items())[:5]}")

# Render de las 4 casetas
for c in range(1, 5):
    render_caseta(c)
    st.markdown("---")

# ---------------- AUDITORÍA ----------------
with st.expander("📜 Historial de movimientos"):
    conn = sqlite3.connect(DB_PATH)
    rows = conn.execute("""SELECT timestamp, unidad_id, valor_anterior, valor_nuevo, delta, motivo
                           FROM movimientos ORDER BY id DESC LIMIT 200""").fetchall()
    conn.close()
    if rows:
        st.dataframe(rows, use_container_width=True,
                     column_config={
                         0: "Fecha", 1: "Unidad", 2: "Antes",
                         3: "Después", 4: "Δ", 5: "Motivo"
                     })
    else:
        st.info("Sin movimientos registrados aún.")

with st.expander("📸 Snapshots guardados"):
    conn = sqlite3.connect(DB_PATH)
    rows = conn.execute("""SELECT fecha, COUNT(*), SUM(poblacion)
                           FROM snapshots GROUP BY fecha ORDER BY fecha DESC""").fetchall()
    conn.close()
    if rows:
        st.dataframe(rows, use_container_width=True,
                     column_config={0: "Fecha", 1: "Unidades", 2: "Total cerdos"})
    else:
        st.info("Sin snapshots guardados aún.")